---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  target-branch: main

- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  target-branch: main
