---
name: build
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: sebastian-toepfer/gh-common/.github/workflows/build.yml@main
    with:
      sonar-projektKey: sebastian-toepfer_pdfbox-fluent-layout
    secrets: inherit
